# Generated by Django 5.0.3 on 2024-06-16 18:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_review_alter_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='background_color',
            field=models.CharField(blank=True, help_text='Cor Tailwind CSS', max_length=7, null=True, verbose_name='Cor de fundo'),
        ),
        migrations.AlterField(
            model_name='product',
            name='review',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Avaliação'),
        ),
    ]
